name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          ./bytes.sh test &&
          /bin/sh README.md &&
          sudo apt-get update &&
          sudo apt-get -y install ghostscript &&
          gs -dBATCH -dNOPAUSE -dPDFSTOPONERROR magic0.zip.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: the-file
          path: magic*.zip.pdf

